webtalk_init -webtalk_dir /home/sr_x/Desktop/Basura/MicroZed/MPL_MZ/MPL_MZ.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 28 02:27:55 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q49cnlkgjuo712eua02nob6h5o" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1509172596000" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.1" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1509172596000"
webtalk_add_data -client sdk -key uid -value "1509172700000" -context "sdk\\\\bsp/1509172700000"
webtalk_add_data -client sdk -key hwid -value "1509172596000" -context "sdk\\\\bsp/1509172700000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1509172700000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1509172700000"
webtalk_add_data -client sdk -key uid -value "1509172710000" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key hwid -value "1509172596000" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key bspid -value "1509172700000" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1509172710000"
webtalk_add_data -client sdk -key uid -value "1509173079000" -context "sdk\\\\application/1509173079000"
webtalk_add_data -client sdk -key hwid -value "1509172596000" -context "sdk\\\\application/1509173079000"
webtalk_add_data -client sdk -key bspid -value "1509172700000" -context "sdk\\\\application/1509173079000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1509173079000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1509173079000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1509173079000"
webtalk_transmit -clientid 46859278 -regid "" -xml /home/sr_x/Desktop/Basura/MicroZed/MPL_MZ/MPL_MZ.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sr_x/Desktop/Basura/MicroZed/MPL_MZ/MPL_MZ.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sr_x/Desktop/Basura/MicroZed/MPL_MZ/MPL_MZ.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
